# Terminotes configuration sample
# Copy this file to ~/.config/terminotes/config.toml and adjust values.

[terminotes]
git_remote_url = "git@github.com:example/terminotes-notes.git"
terminotes_dir = "notes-repo"
editor = "vim"
