# Terminotes configuration sample
# Copy this file to ~/.config/terminotes/config.toml and adjust values.

allowed_tags = ["til", "python", "cli"]
editor = "vim"

[backup]
enabled = true
type = "git"
repo_url = "git@github.com:example/terminotes-notes.git"
